// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_contable.Data;

#nullable disable

namespace Sistema_contable.Migrations
{
    [DbContext(typeof(ContabilidadDbContext))]
    [Migration("20260714050818_LimpiezaTablasMuertas")]
    partial class LimpiezaTablasMuertas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("SistemaContableZulay.UI.Domain.AsientoLinea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoCuenta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ComprobanteContableId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Debe")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionCuenta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Haber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComprobanteContableId");

                    b.ToTable("LineasAsiento");
                });

            modelBuilder.Entity("SistemaContableZulay.UI.Domain.ColaSincronizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Intentos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEntidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ColaSincronizacion");
                });

            modelBuilder.Entity("SistemaContableZulay.UI.Domain.ComprobanteContable", b =>
                {
                    b.Property<int>("IdComprobante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CuentaAsociada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Sincronizado")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdComprobante");

                    b.ToTable("ComprobantesContables");
                });

            modelBuilder.Entity("SistemaContableZulay.UI.Domain.FacturaCobranza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdComprobanteEmision")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdComprobantePago")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdComprobanteReversion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Sincronizado")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FacturasCobranza");
                });

            modelBuilder.Entity("SistemaContableZulay.UI.Domain.PeriodoFiscal", b =>
                {
                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cerrado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Anio", "Mes");

                    b.ToTable("PeriodosFiscales");
                });

            modelBuilder.Entity("SistemaContableZulay.UI.Domain.AsientoLinea", b =>
                {
                    b.HasOne("SistemaContableZulay.UI.Domain.ComprobanteContable", null)
                        .WithMany("Lineas")
                        .HasForeignKey("ComprobanteContableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaContableZulay.UI.Domain.ComprobanteContable", b =>
                {
                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
